version: "3"
services:
  app:
      container_name: covid-19-tracker
      build:
          context: .
          dockerfile: Dockerfile
      entrypoint: ['/etc/startup.sh']
      ports:
          - 5001:5000
      environment:
        - FLASK_ENV=development
        - FLASK_DEBUG=true
      volumes:
        - ${PWD}:/usr/src/www
        - ${PWD}/logs:/tmp/logs
      networks:
        - host

networks:
  host:
